### PURPOSE: Keep UST data only on gas stations using OSM neighbor data, DOE charger data, and major
### station brand names
### LAST EDITED: 12/11/2024
### EDITED FROM: Laptop

library(tm)
library(tidyr)
library(dplyr)
library(ggplot2)
library(usmap)
library(viridis)
library(maps)
library(geoR)
library(mapproj)
library(geosphere)
library(osmdata)
library(httr)
library(jsonlite)
library(sf)
library(nngeo)

###############################################################################################
### Reading in the cleaned UST, charger, and OSM UST neighbor data
###############################################################################################
setwd("H:/My Drive/Research/EV Charging/Data/Cleaned Data")
mergedust <- read.csv("mergedust.csv")
chargerdata <- read.csv("chargerdata.csv")
osm_ust_neighbors <- read.csv("osm stations nearest ust facility.csv")

###############################################################################################
### Keeping only UST facilities that came up as a nearest neighbor to OSM stations
###############################################################################################
matches <- unique(osm_ust_neighbors$facility_id)
length(matches) # 63,815 unique OSM stations matched
osmgasstations <- mergedust[mergedust$facility_id%in%matches,]
length(unique(osmgasstations$facility_id)) # 63,815 so all good

## Renaming rows after dropping observations
rownames(osmgasstations) <- 1:nrow(osmgasstations)

###############################################################################################
### Identifying stations that are identified as gas stations in the DOE charger data (i.e.,
### facility_type=="GAS_STATION" or facility_type=="CONVENIENCE_STORE"
###############################################################################################
## Reading in DOE to UST data matches generated by Stata's geonear function (R's st_nn and st_nearest_feature kept
## identifying the wrong nearest neighbor and grossly incorrect distances to said incorrect nearest neighbor; works fine
## with finding a point's nearest line as is done in the code identifying station's nearest highway though)
doe_identified <- read.csv("doegasstations.csv")

## Extracting UST data for DOE-identified stations and dropping facilities that are already in the OSM-identified station data
doegasstations <- mergedust %>%
  filter(facility_id%in%doe_identified$facility_id) %>%
  filter(!facility_id%in%osmgasstations$facility_id)
  
## Merging osmgasstations (created using OSM data) with doegasstations (created using DOE charger data)
gasstations <- rbind(osmgasstations, doegasstations)

###############################################################################################
### Identifying stations that have a station brand name in their name (e.g., ARCO, 7-Eleven, Royal Farms)
###############################################################################################
## Creating new dataframe of stations that have not been identified via OSM or DOE data (at this point in the code,
## gasstations only contains OSM- and DOE-identified stations, so to avoid double-counting when searching for stations
## by brand name, will only search through stations that are NOT already in gasstations, i.e., that have NOT already been
## identified)
notyetidentified <- mergedust %>%
  filter(!facility_id%in%gasstations$facility_id)

## Creating list of major station brands and keeping stations in notyetidentified that have a brand in their
## name
stationbrands <- c("arco #","buc-ee","casey's general","cefco","cenex","chevron","circle k","citgo",
                   "conoco","cumberland farms","exxon","flying j","gulf","kwik fill","kum and go",
                   "kum & go","kwik trip","maverik","mobil ","quickchek","quiktrip","racetrac",
                   "royal farms","7-eleven","sheetz","stewart's shops","sunoco",
                   "texaco","valero","wawa","arco am","arco 0","arco 4","arco 5","arco 67",
                   "arco 7","arco 8","speedway store","speedway #","speedway 1","speedway 2",
                   "speedway 3","speedway 4","speedway 5","speedway 6","speedway 7","speedway 8")
brandgasstations <- list()
for (i in 1:length(stationbrands)) {
  brand <- stationbrands[i]
  print(paste0("Working on brand ", i, " of ", length(stationbrands)))
  brandgasstations[[i]] <- notyetidentified %>% 
    filter(grepl(brand, name, ignore.case=TRUE))
}
brandgasstations <- do.call(rbind, brandgasstations)
brandgasstations <- as.data.frame(brandgasstations)
rownames(brandgasstations) <- 1:nrow(brandgasstations)

## Removing repeats (for stations with two brands in their name, like "ExxonMobil" or "Chevron Circle K")
# Recording number of times stations appear in original notyetidentified data for reference and adding it to
# brandgasstations
numobs <- notyetidentified %>% 
  group_by(facility_id) %>% 
  dplyr::summarise(n=n()) %>%
  ungroup()
brandgasstations <- left_join(brandgasstations, numobs, by="facility_id")
# Creating variable for number of times each facility appears in brandgasstations (this needs to match
# each facility's corresponding count in 'numobs')
brandgasstations <- brandgasstations %>% 
  group_by(facility_id) %>% 
  dplyr::mutate(count=row_number()) %>%
  ungroup()
# Filtering out observations whose row count is greater than their number of original observations in
# notyetidentified (contained in numobs vector) and then dropping the n and count variables
brandgasstations <- brandgasstations %>% 
  group_by(facility_id) %>% 
  dplyr::filter(count<=n) %>%
  ungroup() %>%
  select(!c(n, count))

## Removing stations with ExxonMobil in name (these are refineries, terminals, or plants)
brandgasstations <- brandgasstations %>% 
  filter(!grepl("exxonmobil", name, ignore.case=TRUE))

## Merging gasstations (created using OSM data and now DOE charger data too) with brandgasstations
## (created using major station brand names)
gasstations <- rbind(gasstations, brandgasstations)

###############################################################################################
### Dropping observations for stations that are part of a supermarket chain (e.g., Costco)
###############################################################################################
supermarkets <- c("Costco","Kroger","Harris Teeter","Sams Club","Sam's Club","Walmart","Albertsons",
                  "Albertson's","Vons Fuel Center","Vons ","Safeway","ACME FOODS FUEL CENTER",
                  "STOP AND SHOP #726","stop and shop fueling","king soopers","smith's food & drug",
                  "smith's fuel center","fred meyer","food 4 less","city market #","city market fuel",
                  "ralphs fuel","hy-vee","meijer","giant eagle","food city gas","food city express",
                  "food city 8","food city #","ingles i","ingles gas","piggly wiggly","buehlers",
                  "county market","festival foods","foodland plus fuel center","TOWN N COUNTRY FOODLAND",
                  "foodland express","redner","sendiks fresh","Daniels Sentry Foods","sullivans foods",
                  "sullivan's foods","woodmans","woodman's","99 cents only","dollar general",
                  "save-a-lot","heb","raley","save mart","s-mart","winco","schnucks","weis mkt",
                  "weis gas n","weis gas &","weis market","ingles market","acme express",
                  "big y","harmons","lowes fuel","lowes food","price chopper","rosauer","rouses",
                  "hvyee","hy vee","giant","holiday","stop & shop fuel","stop and shop","gerbes",
                  "wal-mart","acme","stop & shop","smith's food and drug","smith's #448","ralphs  ",
                  "hyvee","ingles ","foodland","sendiks","save a lot","harmon's")
## Looping through supermarkets to remove them
for (j in 1:length(supermarkets)) {
  supermarket <- supermarkets[j]
  print(paste0("Working on market ", j, " of ", length(supermarkets)))
  gasstations <- gasstations %>% 
    filter(!grepl(supermarkets[j], name, ignore.case=TRUE))
}
gasstations <- as.data.frame(gasstations)
rownames(gasstations) <- 1:nrow(gasstations)

## Saving gas stations dataset gasstations
write.csv(gasstations, file="gasstations.csv", row.names=FALSE)
  # Note: 72,628 unique gas stations spanning the contiguous U.S. and DC.

## Clearing the environment
rm(list=ls())